version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hotel-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: hotel_buchung_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  springboot-app:
    build: .
    container_name: hotel-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hotel_buchung_db
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
